import { Router } from 'express';
import AgenteController from '../controllers/AgenteController';
const router = Router();
router.get('/data/:page/:num/:prop/:orden',AgenteController.getData);
router.get('/list/:prop/:value', AgenteController.getList);
router.get('/items/:prop/:value', AgenteController.getItems);
router.get('/:id',AgenteController.getItem);
router.post('/:tipo',AgenteController.setAdd);
router.put('/:id/:tipo',AgenteController.setUpdate);
router.delete('/:id/:tipo',AgenteController.getDelete);
router.post('/search/lista',AgenteController.getSearch);
export default router;
